export const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST";
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
export const PRODUCTS_LIST_FAIL = "PRODUCTS_LIST_FAIL";

export const PRODUCTS_DETAILS_REQUEST = "PRODUCTS_DETAILS_REQUEST";
export const PRODUCTS_DETAILS_SUCCESS = "PRODUCTS_DETAILS_SUCCESS";
export const PRODUCTS_DETAILS_FAIL = "PRODUCTS_DETAILS_FAIL";

export const PRODUCTS_HISTORY_REQUEST = "PRODUCTS_HISTORY_REQUEST";
export const PRODUCTS_HISTORY_SUCCESS = "PRODUCTS_HISTORY_SUCCESS";
export const PRODUCTS_HISTORY_FAIL = "PRODUCTS_HISTORY_FAIL";
